import type { CSSProperties } from "react";

export const COLORI_CHAT_GLOBAL = {
  homeBackground: "#FFFFFF",
  chatPanel: "#F8FAFC",
  surface: "#FFFFFF",
  surfaceSoft: "#F8FAFC",
  border: "#D1D5DB",
  textPrimary: "#111827",
  textMuted: "#6B7280",
  textSecondary: "#374151",
  textTertiary: "#9CA3AF",
  avatarFallbackBg: "#E5E7EB",
  surfaceDeep: "#F3F4F6",
  tooltipBg: "#111827",
  tooltipBorder: "#1F2937",
  successDot: "#16A34A",
  successStroke: "#BBF7D0",
  resizeHandleIcon: "#6B7280",
  danger: "#DC2626",
  infoBadgeBg: "#DBEAFE",
  infoBadgeText: "#1E3A8A",
  warningBadgeBg: "#FEF3C7",
  warningBadgeText: "#78350F",
  buttonPrimaryBg: "#111827",
  buttonPrimaryText: "#FFFFFF",
  buttonPrimaryHoverBg: "#1F2937",
  roomButtonBackground: "#FFFFFF",
  roomButtonBorder: "#D1D5DB",
  roomButtonText: "#111827",
  roomButtonHoverBackground: "#D1D5DB",
  roomDropdownBackground: "#FFFFFF",
  roomDropdownBorder: "#D1D5DB",
  roomItemText: "#111827",
  roomItemHoverBackground: "#F8FAFC",
  roomItemActiveBackground: "#F8FAFC",
  roomFocusRing: "#D1D5DB",
  headerActionBackground: "#FFFFFF",
  headerActionBorder: "#D1D5DB",
  headerActionText: "#111827",
  headerActionHoverBackground: "#D1D5DB",
  headerActionFocusRing: "#D1D5DB",
} as const;

export const COLORI_CHAT_GLOBAL_CSS_VARS: CSSProperties = {
  ["--gc-home-bg" as string]: COLORI_CHAT_GLOBAL.homeBackground,
  ["--gc-chat-panel" as string]: COLORI_CHAT_GLOBAL.chatPanel,
  ["--gc-surface" as string]: COLORI_CHAT_GLOBAL.surface,
  ["--gc-surface-soft" as string]: COLORI_CHAT_GLOBAL.surfaceSoft,
  ["--gc-border" as string]: COLORI_CHAT_GLOBAL.border,
  ["--gc-text-primary" as string]: COLORI_CHAT_GLOBAL.textPrimary,
  ["--gc-text-muted" as string]: COLORI_CHAT_GLOBAL.textMuted,
  ["--gc-text-secondary" as string]: COLORI_CHAT_GLOBAL.textSecondary,
  ["--gc-text-tertiary" as string]: COLORI_CHAT_GLOBAL.textTertiary,
  ["--gc-avatar-fallback-bg" as string]: COLORI_CHAT_GLOBAL.avatarFallbackBg,
  ["--gc-surface-deep" as string]: COLORI_CHAT_GLOBAL.surfaceDeep,
  ["--gc-tooltip-bg" as string]: COLORI_CHAT_GLOBAL.tooltipBg,
  ["--gc-tooltip-border" as string]: COLORI_CHAT_GLOBAL.tooltipBorder,
  ["--gc-success-dot" as string]: COLORI_CHAT_GLOBAL.successDot,
  ["--gc-success-stroke" as string]: COLORI_CHAT_GLOBAL.successStroke,
  ["--gc-resize-handle-icon" as string]: COLORI_CHAT_GLOBAL.resizeHandleIcon,
  ["--gc-danger" as string]: COLORI_CHAT_GLOBAL.danger,
  ["--gc-info-badge-bg" as string]: COLORI_CHAT_GLOBAL.infoBadgeBg,
  ["--gc-info-badge-text" as string]: COLORI_CHAT_GLOBAL.infoBadgeText,
  ["--gc-warning-badge-bg" as string]: COLORI_CHAT_GLOBAL.warningBadgeBg,
  ["--gc-warning-badge-text" as string]: COLORI_CHAT_GLOBAL.warningBadgeText,
  ["--gc-button-primary-bg" as string]: COLORI_CHAT_GLOBAL.buttonPrimaryBg,
  ["--gc-button-primary-text" as string]: COLORI_CHAT_GLOBAL.buttonPrimaryText,
  ["--gc-button-primary-hover-bg" as string]: COLORI_CHAT_GLOBAL.buttonPrimaryHoverBg,
  ["--gc-room-button-bg" as string]: COLORI_CHAT_GLOBAL.roomButtonBackground,
  ["--gc-room-button-border" as string]: COLORI_CHAT_GLOBAL.roomButtonBorder,
  ["--gc-room-button-text" as string]: COLORI_CHAT_GLOBAL.roomButtonText,
  ["--gc-room-button-hover-bg" as string]: COLORI_CHAT_GLOBAL.roomButtonHoverBackground,
  ["--gc-room-dropdown-bg" as string]: COLORI_CHAT_GLOBAL.roomDropdownBackground,
  ["--gc-room-dropdown-border" as string]: COLORI_CHAT_GLOBAL.roomDropdownBorder,
  ["--gc-room-item-text" as string]: COLORI_CHAT_GLOBAL.roomItemText,
  ["--gc-room-item-hover-bg" as string]: COLORI_CHAT_GLOBAL.roomItemHoverBackground,
  ["--gc-room-item-active-bg" as string]: COLORI_CHAT_GLOBAL.roomItemActiveBackground,
  ["--gc-room-focus-ring" as string]: COLORI_CHAT_GLOBAL.roomFocusRing,
  ["--gc-header-action-bg" as string]: COLORI_CHAT_GLOBAL.headerActionBackground,
  ["--gc-header-action-border" as string]: COLORI_CHAT_GLOBAL.headerActionBorder,
  ["--gc-header-action-text" as string]: COLORI_CHAT_GLOBAL.headerActionText,
  ["--gc-header-action-hover-bg" as string]: COLORI_CHAT_GLOBAL.headerActionHoverBackground,
  ["--gc-header-action-focus-ring" as string]: COLORI_CHAT_GLOBAL.headerActionFocusRing,
};
