import type { CSSProperties } from "react";

export const COLORI_CHAT_GLOBAL = {
  homeBackground: "#13232D",
  chatPanel: "#1A2E39",
  surface: "#13232D",
  surfaceSoft: "#1A2E39",
  border: "#395565",
  textPrimary: "#FFFFFF",
  textMuted: "#9CA3AF",
  textSecondary: "#D1D5DB",
  textTertiary: "#A1A1AA",
  avatarFallbackBg: "#151515",
  surfaceDeep: "#161923",
  tooltipBg: "#000000",
  tooltipBorder: "#101010",
  successDot: "#04DC3A",
  successStroke: "#B8FFC0",
  resizeHandleIcon: "#D6E2EF",
  danger: "#FF0000",
  infoBadgeBg: "#35546A",
  infoBadgeText: "#D8ECFF",
  warningBadgeBg: "#6F5D1F",
  warningBadgeText: "#FFF4BF",
  buttonPrimaryBg: "#FFFFFF",
  buttonPrimaryText: "#000000",
  buttonPrimaryHoverBg: "#E4E4E7",
} as const;

export const COLORI_CHAT_GLOBAL_CSS_VARS: CSSProperties = {
  ["--gc-home-bg" as string]: COLORI_CHAT_GLOBAL.homeBackground,
  ["--gc-chat-panel" as string]: COLORI_CHAT_GLOBAL.chatPanel,
  ["--gc-surface" as string]: COLORI_CHAT_GLOBAL.surface,
  ["--gc-surface-soft" as string]: COLORI_CHAT_GLOBAL.surfaceSoft,
  ["--gc-border" as string]: COLORI_CHAT_GLOBAL.border,
  ["--gc-text-primary" as string]: COLORI_CHAT_GLOBAL.textPrimary,
  ["--gc-text-muted" as string]: COLORI_CHAT_GLOBAL.textMuted,
  ["--gc-text-secondary" as string]: COLORI_CHAT_GLOBAL.textSecondary,
  ["--gc-text-tertiary" as string]: COLORI_CHAT_GLOBAL.textTertiary,
  ["--gc-avatar-fallback-bg" as string]: COLORI_CHAT_GLOBAL.avatarFallbackBg,
  ["--gc-surface-deep" as string]: COLORI_CHAT_GLOBAL.surfaceDeep,
  ["--gc-tooltip-bg" as string]: COLORI_CHAT_GLOBAL.tooltipBg,
  ["--gc-tooltip-border" as string]: COLORI_CHAT_GLOBAL.tooltipBorder,
  ["--gc-success-dot" as string]: COLORI_CHAT_GLOBAL.successDot,
  ["--gc-success-stroke" as string]: COLORI_CHAT_GLOBAL.successStroke,
  ["--gc-resize-handle-icon" as string]: COLORI_CHAT_GLOBAL.resizeHandleIcon,
  ["--gc-danger" as string]: COLORI_CHAT_GLOBAL.danger,
  ["--gc-info-badge-bg" as string]: COLORI_CHAT_GLOBAL.infoBadgeBg,
  ["--gc-info-badge-text" as string]: COLORI_CHAT_GLOBAL.infoBadgeText,
  ["--gc-warning-badge-bg" as string]: COLORI_CHAT_GLOBAL.warningBadgeBg,
  ["--gc-warning-badge-text" as string]: COLORI_CHAT_GLOBAL.warningBadgeText,
  ["--gc-button-primary-bg" as string]: COLORI_CHAT_GLOBAL.buttonPrimaryBg,
  ["--gc-button-primary-text" as string]: COLORI_CHAT_GLOBAL.buttonPrimaryText,
  ["--gc-button-primary-hover-bg" as string]: COLORI_CHAT_GLOBAL.buttonPrimaryHoverBg,
};
