-- Search analytics events used for real trending searches.
create table if not exists public.search_query_events (
  id bigint generated by default as identity primary key,
  query_text text not null check (char_length(trim(query_text)) between 2 and 120),
  query_norm text not null check (char_length(trim(query_norm)) between 2 and 120),
  scope text null check (scope in ('users', 'services', 'products', 'wallet', 'pages', 'verified-sellers')),
  source text not null default 'cmdk',
  selected_item_id text null,
  intent text null,
  entities jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create index if not exists search_query_events_created_at_idx
  on public.search_query_events (created_at desc);

create index if not exists search_query_events_query_norm_idx
  on public.search_query_events (query_norm);

create index if not exists search_query_events_scope_created_at_idx
  on public.search_query_events (scope, created_at desc);

create index if not exists search_query_events_source_idx
  on public.search_query_events (source);

-- Real trending terms from query events.
create or replace function public.get_trending_searches(
  hours_window integer default 168,
  limit_count integer default 8,
  scope_filter text default null
)
returns table(query text, search_count bigint)
language sql
stable
as $$
  select
    sqe.query_norm as query,
    count(*) as search_count
  from public.search_query_events sqe
  where sqe.created_at >= now() - make_interval(hours => greatest(hours_window, 1))
    and (scope_filter is null or sqe.scope = scope_filter)
  group by sqe.query_norm
  having count(*) >= 2
  order by count(*) desc, max(sqe.created_at) desc
  limit greatest(limit_count, 1);
$$;

